name: mesa-core22
base: core22
summary: mesa libraries for core22 snaps
description: |
  A content snap containing the mesa libraries and drivers for core 22
compression: lzo
version: "0.01"

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x
  - build-on: riscv64

parts:
  i386-repo:
    plugin: nil
    override-pull: |
      if [ ${CRAFT_TARGET_ARCH} = "amd64" ]; then
        dpkg --add-architecture i386
        apt-get update
      fi

  apis:
    # This provides the essential APIs
    #   o libEGL.so.1
    #   o libva.so.2
    #   o libvulkan.so.1
    #   o libGLX.so.0
    #
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libegl1
      - libgles2
      - libvulkan1
      - libglx0
    prime:
      - usr/lib
      - usr/share/glvnd

  drm:
    # DRM userspace
    #   o libdrm.so.2
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libdrm2
    prime:
      - usr/lib

  va:
    # Video Acceleration API
    #   o libva.so.2
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libva2
    prime:
      - usr/lib

  dri:
    # Userspace drivers
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all
      - vdpau-driver-all
      - mesa-vulkan-drivers
      - libglx-mesa0
    prime:
      - usr/lib
      - usr/share/vulkan
      - usr/share/drirc.d

  x11:
    # X11 support (not much cost to having this)
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libva-x11-2
      - libx11-xcb1
      - libxau6
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-present0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb1
      - libxdamage1
      - libxdmcp6
      - libxshmfence1
    prime:
      - usr/lib
      - usr/share/X11

  wayland:
    # Wayland support (not much cost to having this)
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - libwayland-client0
      - libwayland-egl1
      - libwayland-server0
    prime:
      - usr/lib

  apis-i386:
      # This provides the essential APIs
      #   o libEGL.so.1
      #   o libva.so.2
      #   o libvulkan.so.1
      #   o libGLX.so.0
      #
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libegl1:i386
        - libgles2:i386
        - libvulkan1:i386
        - libglx0:i386
    override-prime: |
      if [ `arch` = "x86_64" ]; then craftctl default; fi
    prime:
      - usr/lib
      - usr/share/glvnd

  drm-i386:
    # DRM userspace
    #   o libdrm.so.2
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libdrm2:i386
    override-prime: |
      if [ `arch` = "x86_64" ]; then craftctl default; fi
    prime:
      - usr/lib

  va-i386:
    # Video Acceleration API
    #   o libva.so.2
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libva2:i386
    override-prime: |
      if [ `arch` = "x86_64" ]; then craftctl default; fi
    prime:
      - usr/lib

  dri-i386:
    # Userspace drivers
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libgl1-mesa-dri:i386
        - va-driver-all:i386
        - vdpau-driver-all:i386
        - mesa-vulkan-drivers:i386
        - libglx-mesa0:i386
    override-prime: |
      if [ `arch` = "x86_64" ]; then craftctl default; fi
    prime:
      - usr/lib
      - usr/share/vulkan
      - usr/share/drirc.d

  x11-i386:
    # X11 support (not much cost to having this)
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libva-x11-2:i386
        - libx11-xcb1:i386
        - libxau6:i386
        - libxcb-dri2-0:i386
        - libxcb-dri3-0:i386
        - libxcb-present0:i386
        - libxcb-sync1:i386
        - libxcb-xfixes0:i386
        - libxcb1:i386
        - libxdamage1:i386
        - libxdmcp6:i386
        - libxshmfence1:i386
    override-prime: |
      if [ `arch` = "x86_64" ]; then craftctl default; fi
    prime:
      - usr/lib
      - usr/share/X11

  wayland-i386:
    # Wayland support (not much cost to having this)
    after: [i386-repo]  # because LP#2009278
    plugin: nil
    stage-packages:
      - on amd64:
        - libwayland-client0:i386
        - libwayland-egl1:i386
        - libwayland-server0:i386
    override-prime: |
      if [ `arch` = "x86_64" ]; then craftctl default; fi
    prime:
      - usr/lib

slots:
  graphics-core22:
    interface: content
    source:
      read:
        - $SNAP/usr/lib
        - $SNAP/usr/share
